name: Deploy documentation

on:
  push:
    tags: 
      - v*
      - d*

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy MkDocs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.11
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
